name: Regression

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  linux:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout
     uses: actions/checkout@v4
   - name: Set up Python 3.12
     uses: actions/setup-python@v5
     with:
       python-version: 3.12
   - name: Update pip
     run: python -m pip install --upgrade pip
   - name: Run regression test
     run: source regress.sh

  mac:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        allow-prereleases: true
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: Run regression test
      run: source regress.sh
