name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: Run regression test
      run: source regress.sh
    - name: Build source distribution
      run: python setup.py sdist
    - name: Publish source distribution to PyPI
      run: |
        pip install twine
        twine upload dist/*
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
